name: Deploy to Hugging Face Space

on:
  push:
    branches:
      - main  # Trigger workflow when pushing to main branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Push to Hugging Face Space
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://$HF_TOKEN@huggingface.co/spaces/crurbina97/sentiment-analysis
          git fetch hf
          git push hf main --force