name: Deploy Clean Branch to Hugging Face

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repository
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # 2. Configure Git
      - run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      # 3. Create clean branch and ignore assets/
      - run: |
          git checkout --orphan hf-main
          git rm -rf assets || true       # remove assets folder
          git add .
          git commit -m "Deploy clean branch to HF"

      # 4. Push to Hugging Face
      - env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git remote add hf https://user:$HF_TOKEN@huggingface.co/spaces/crurbina97/sentiment-analysis
          git push hf hf-main:main --force

      # 5. Return to main
      - run: git checkout main